export const en = {
  fr: 'French',
  en: 'English',
  home: 'Home',
  store: 'Store',
  salePoints: 'Sale points',
  about: 'About us',
  settings: 'Réglages',
  carousel: 'Carousel',
  preview: 'Preview',
  logout: 'Logout',
  titlePlaceholder: 'Enter a title',
  descriptionPlaceholder: 'Enter a description',
  iconPlaceholder: 'Enter a "Font Awsome" icon name',
  addressPlaceholder: 'Enter an address',
  textareaPlaceholder: 'Write something...',
  addImage: 'Add an image',
  addLocation: 'Add a location',
  addPost: 'Add a post',
  loading: 'Loading',
  searchMapPlaceholder: 'Enter an address or a postal code',
  getCurrentLocation: 'Get curent location',
  seeInMaps: 'See in Google Maps',
  copy: 'Copy'

}
