export const en = {
  fr: 'French',
  en: 'English',
  home: 'Home',
  store: 'Store',
  salePoints: 'Sale points',
  about: 'About us',
  settings: 'Réglages',
  carousel: 'Carousel',
  preview: 'Preview',
  logout: 'Logout',
  titlePlaceholder: 'Enter a title',
  namePlaceholder: 'Enter a name',
  descriptionPlaceholder: 'Enter a description',
  iconPlaceholder: 'Enter a "Font Awsome" icon name',
  addressPlaceholder: 'Enter an address',
  textareaPlaceholder: 'Write something...',
  searchMapPlaceholder: 'Enter an address',
  categoryPlaceholder: 'Select a category',
  countPlaceholder: 'Enter the invetory count',
  frNamePlaceholder: 'Enter a name (french)',
  enNamePlaceholder: 'Enter a name (english)',
  addImage: 'Add an image',
  addLocation: 'Add a location',
  addPost: 'Add a post',
  addPocket: 'Add a pocket',
  addCategory: 'Add a category',
  addStraw: 'Add a straw',
  addBrush: 'Add a brush',
  loading: 'Loading',
  getCurrentLocation: 'Get curent location',
  seeInMaps: 'See in Google Maps',
  copy: 'Copy',
  articles: 'Articles',
  categories: 'Categories',
  allModels: 'All models',
  back: 'Back',
  next: 'Next',
  quantity: 'Quantity',
  stock: 'In stock',
  addCart: 'Add to cart',
  buy: 'Buy',
  productName: 'Product name : ',
  productDescription: 'Product description :',
  pocket: 'Pocket',
  straw: 'Straw',
  quantityPlaceholder: 'Select a quantity',
  brush: 'Brush',
  category: 'Pocket categories',
  style: 'Style',
  Quantity: 'Quantity',
  cart: 'Cart',
  pockets: 'Pockets',
  straws: 'Straws',
  brushes: 'Brushes',
  price: 'Price ',
  totalPrice: 'Total price : '
}
