export const fr = {
  fr: 'Français',
  en: 'Anglais',
  home: 'Accueil',
  store: 'Magasin',
  salePoints: 'Points de vente',
  about: 'À propos',
  settings: 'Settings',
  carousel: 'Carousel',
  preview: 'Aperçu',
  logout: 'Déconnexion',
  titlePlaceholder: 'Entrer un title',
  descriptionPlaceholder: 'Entrer une description',
  iconPlaceholder: 'Entrer un nom d\'icon "Font Awsome"',
  addressPlaceholder: 'Entrer une adresse',
  textareaPlaceholder: 'Écrire quelque chose...',
  addImage: 'Ajouter une image',
  addLocation: 'Ajouter une localisation',
  addPost: 'Ajouter une publication',
  loading: 'Chargement',
  searchMapPlaceholder: 'Entrer une adresse ou un code postal',
  getCurrentLocation: 'Utiliser mon emplacement',
  seeInMaps: 'Voir dans Google Maps',
  copy: 'Copier'

}
