export const fr = {
  fr: 'Français',
  en: 'Anglais',
  home: 'Accueil',
  store: 'Magasin',
  salePoints: 'Points de vente',
  about: 'À propos',
  settings: 'Settings',
  carousel: 'Carousel',
  preview: 'Aperçu',
  logout: 'Déconnexion',
  titlePlaceholder: 'Entrer un title',
  namePlaceholder: 'Entrer un nom',
  descriptionPlaceholder: 'Entrer une description',
  iconPlaceholder: 'Entrer un nom d\'icon "Font Awsome"',
  addressPlaceholder: 'Entrer une adresse',
  textareaPlaceholder: 'Écrire quelque chose...',
  searchMapPlaceholder: 'Entrer une adresse ou un code postal',
  categoryPlaceholder: 'Choisir une catégorie',
  countPlaceholder: 'Entrer la quantité en inventaire',
  frNamePlaceholder: 'Entrer un nom (français)',
  enNamePlaceholder: 'Entrer un nom (anglais)',
  addImage: 'Ajouter une image',
  addLocation: 'Ajouter une localisation',
  addPost: 'Ajouter une publication',
  addPocket: 'Ajouter une pochette',
  addCategory: 'Ajouter une catégorie',
  addStraw: 'Ajouter une paille',
  addBrush: 'Ajouter une brosse',
  loading: 'Chargement',
  getCurrentLocation: 'Utiliser mon emplacement',
  seeInMaps: 'Voir dans Google Maps',
  copy: 'Copier',
  articles: 'Articles',
  categories: 'Catégories de pochettes',
  allModels: 'Tous les modèles',
  back: 'Retour',
  next: 'Suivant',
  quantity: 'Quantité',
  stock: 'En stock',
  addCart: 'Ajouter au panier',
  buy: 'Acheter',
  productName: 'Nom de produit',
  productDescription: 'Description du produit',
  pocket: 'Pochette',
  category: 'Catégories',
  Quantity: 'Qunatité',
  straw: 'Paille',
  brush: 'Brosse',
  quantityPlaceholder: 'Sélectionnez une quantité',
  cart: 'Panier',
  pockets: 'Pochettes',
  straws: 'Pailles',
  brushes: 'Brosses',
  price: 'Prix ',
  totalPrice: 'Prix total : '
}
